server:
  port: 8899
spring:
  application:
    name: example-app
  zipkin:
    base-url: 192.168.0.105:9411
    sender:
      type: kafka
    service:
      name: ${spring.application.name}
  sleuth:
    sampler:
      probability: 1.0
  kafka:
    bootstrap-servers: 192.168.0.105:9092
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev

halo:
  log:
    enable: true
