version: '3.7'
services:
  zookeeper:
    image: zookeeper
    volumes:
      - ./data:/data
    ports:
      - 2182:2181
       
  kafka001:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.0.105:9092
      # KAFKA_CREATE_TOPICS: "kafeidou:2:0"   #kafka启动后初始化一个有2个partition(分区)0个副本名叫kafeidou的topic 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    volumes:
      - ./kafka-logs:/kafka
    depends_on:
      - zookeeper
  kafka-manager:
    image: hlebalbau/kafka-manager
    container_name: kafka-manager
    ports:
      - 9000:9000
    # networks:
    #   - kafka-net
    environment:
      ZK_HOSTS: zookeeper:2181
    depends_on:
      - zookeeper
  